# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InfoSDU' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InfoSDU
  pod 'Cartography'
  pod 'SwiftSoup'
  pod 'Alamofire', '~> 4.6'
  pod 'GoogleMaps'
  pod 'GooglePlaces'

  target 'InfoSDUTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InfoSDUUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
