# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sushi' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Cartography'
  pod 'PMAlertController'
  pod 'Cosmos'
  pod 'AAPickerView'
  pod 'SwiftyButton'
  pod 'ZKCarousel'
  # Pods for Sushi

end
